package:
  name: conda_build_issue
  version: "2.0.0"

source:
  path: ..

build:
  entry_points:
    - hello=conda_build_issue.hello:main

requirements:

  build:
    - pysoundfile
    - python
    - setuptools

  run:
    - pysoundfile
    - python
